{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ default .Release.Namespace .Values.settings.namespace }}
  name: {{ include "vault-autounseal.fullname" . }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "list", "delete", "update", "patch"]
  resourceNames:
  - {{ default (printf "%s-%s" (include "vault-autounseal.fullname" .) "root-token") (index .Values.settings "vault-root-token-secret") }}
  - {{ default (printf "%s-%s" (include "vault-autounseal.fullname" .) "unlock-keys") (index .Values.settings "vault-unlock-keys-secret" ) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ default .Release.Namespace .Values.settings.namespace }}
  name: {{ include "vault-autounseal.fullname" . }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault-autounseal.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "vault-autounseal.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.vault.namespace }}
  name: {{ include "vault-autounseal.fullname" . }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list" ]
  resourceNames:
  - {{ .Values.vault.internalService  }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.vault.namespace }}
  name: {{ include "vault-autounseal.fullname" . }}
  labels:
    {{- include "vault-autounseal.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "vault-autounseal.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "vault-autounseal.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
