kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-cert-creator.serviceAccountName" . }}
  labels:
    {{- include "vault-cert-creator.labels" . | nindent 4 }}
  namespace: {{ default .Release.Namespace .Values.settings.vaultNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - delete
  - update
  - patch
  resourceNames:
  - {{ .Values.settings.tlsSecretName }}
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
  - create
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "vault-cert-creator.serviceAccountName" . }}
  labels:
    {{- include "vault-cert-creator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - create
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - patch
  - watch
  - delete
  - update
  resourceNames:
  - {{ .Values.settings.csrName }}
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
  resourceNames:
  - {{ .Values.settings.csrName }}
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/kubelet-serving
  verbs:
  - approve
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-cert-creator.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.settings.vaultNamespace }}
  labels:
    {{- include "vault-cert-creator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-cert-creator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-cert-creator.serviceAccountName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vault-cert-creator.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.settings.vaultNamespace }}
  labels:
    {{- include "vault-cert-creator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-cert-creator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vault-cert-creator.serviceAccountName" . }}
